# -*- coding: utf-8 -*-
"""inequacao-pinheiro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ri9mrG3mThhoFakrZH8UtPpP5In5_q3
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_inequacao_linear(a, b, simbolo):
    """
    Desenha a área de solução para a inequação y [simbolo] ax + b.
    """
    # 1. Configuração dos dados
    x = np.linspace(-10, 10, 400)
    y_linha = a * x + b

    # Configuração do gráfico
    plt.figure(figsize=(8, 6))
    plt.axhline(0, color='black', linewidth=1) # Eixo X
    plt.axvline(0, color='black', linewidth=1) # Eixo Y

    # 2. Definição do estilo da linha e preenchimento
    # Se for estritamente > ou <, a linha é tracejada. Se for >= ou <=, é sólida.
    estilo_linha = '--' if simbolo in ['>', '<'] else '-'
    label_linha = f'y = {a}x + {b}'

    # Desenha a linha limite
    plt.plot(x, y_linha, linestyle=estilo_linha, color='red', label=label_linha)

    # 3. Lógica de preenchimento da área de solução
    # Definimos um limite superior/inferior bem alto para o preenchimento
    y_max = np.max(y_linha) + 50
    y_min = np.min(y_linha) - 50

    if simbolo in ['>', '>=']:
        plt.fill_between(x, y_linha, y_max, color='skyblue', alpha=0.4, label='Área de Solução')
    elif simbolo in ['<', '<=']:
        plt.fill_between(x, y_linha, y_min, color='skyblue', alpha=0.4, label='Área de Solução')
    else:
        print("Símbolo de inequação inválido!")
        return

    # Customização final
    plt.title(f'Solução da Inequação: $y {simbolo} {a}x + {b}$')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.legend()
    plt.xlim(-10, 10)
    plt.ylim(min(y_linha)-5, max(y_linha)+5)

    plt.show()

# --- Exemplo de Uso ---
# Para a inequação y >= 2x + 3
plot_inequacao_linear(a=2, b=3, simbolo='>=')