# -*- coding: utf-8 -*-
"""ineq-pinheiro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUdD-kVqMgmsPrGJcDPt2cMVoZg-SARb
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_sistema_inequacoes():
    print("Configuração do Sistema de Inequações (Primeiro Quadrante)")
    print("Formato esperado: a1X + a2Y SINAL valorDireito")
    print("Exemplo: 1X + 2Y <= 10")
    print("Sinais aceitos: <, <=, >, >=")

    inequacoes = []
    while True:
        entrada = input("\nDigite a inequação (ou 'sair' para plotar): ").strip().lower()
        if entrada == 'sair':
            break
        try:
            # Parsing básico da string
            partes = entrada.replace(' ', '').split('x+')
            a1 = float(partes[0])

            # Identifica o sinal e separa o resto
            sinal = None
            for s in ['<=', '>=', '<', '>']:
                if s in partes[1]:
                    sinal = s
                    break

            sub_partes = partes[1].split(sinal)
            a2 = float(sub_partes[0].replace('y', ''))
            valor_direito = float(sub_partes[1])

            inequacoes.append({'a1': a1, 'a2': a2, 'sinal': sinal, 'valor': valor_direito})
        except Exception as e:
            print(f"Erro ao processar entrada. Certifique-se de usar o formato correto. Erro: {e}")

    if not inequacoes:
        return

    # 1. Configuração da grade (Primeiro Quadrante)
    # Define um limite baseado nos valores direitos para garantir visibilidade
    limite = max([abs(i['valor']) for i in inequacoes]) + 5
    x = np.linspace(0, limite, 400)
    y = np.linspace(0, limite, 400)
    X, Y = np.meshgrid(x, y)

    plt.figure(figsize=(10, 8))

    # Máscara inicial: todos os pontos no primeiro quadrante (True)
    intersecao = (X >= 0) & (Y >= 0)

    # 2. Processamento das Inequações
    for i, inequacao in enumerate(inequacoes):
        a1, a2, sinal, v = inequacao['a1'], inequacao['a2'], inequacao['sinal'], inequacao['valor']

        # Calcula a expressão para a grade
        expressao = a1 * X + a2 * Y

        # Cria a máscara para a inequação atual
        if sinal == '<':
            mask = expressao < v
            estilo = '--'
        elif sinal == '<=':
            mask = expressao <= v
            estilo = '-'
        elif sinal == '>':
            mask = expressao > v
            estilo = '--'
        elif sinal == '>=':
            mask = expressao >= v
            estilo = '-'

        # Atualiza a interseção (Lógica AND)
        intersecao &= mask

        # Traça a linha limite da inequação
        # a1X + a2Y = v  =>  Y = (v - a1X) / a2
        if a2 != 0:
            y_linha = (v - a1 * x) / a2
            plt.plot(x, y_linha, linestyle=estilo, label=f"{a1}x + {a2}y {sinal} {v}")
        else: # Caso vertical (a2 = 0)
            plt.axvline(v/a1, linestyle=estilo, label=f"{a1}x {sinal} {v}")

    # 3. Destacar a área de interseção
    plt.imshow(intersecao.astype(int), extent=(0, limite, 0, limite),
               origin='lower', cmap='Blues', alpha=0.3)

    # Configurações do Gráfico
    plt.axhline(0, color='black', linewidth=1)
    plt.axvline(0, color='black', linewidth=1)
    plt.xlim(0, limite)
    plt.ylim(0, limite)
    plt.xlabel('Eixo X')
    plt.ylabel('Eixo Y')
    plt.title('Interseção do Sistema de Inequações (1º Quadrante)')
    plt.legend()
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.show()

# Executar o algoritmo
plot_sistema_inequacoes()